steps:
  # - name: "gcr.io/cloud-builders/docker"
  # args: ["pull", "gcr.io/skyscraper-sdr/pybombs-arm:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/skyscraper-sdr/pybombs-arm:latest",
        "--cache-from",
        "gcr.io/skyscraper-sdr/pybombs-arm:latest",
        "-f",
        "./base-images/pybombs-slim/armhf.dockerfile",
        "./base-images/pybombs-slim/",
      ]
    timeout: 8h
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/skyscraper-sdr/pybombs-arm:latest"]
images: ["gcr.io/skyscraper-sdr/pybombs-arm:latest"]
timeout: 8h30m
